### PR TITLE
fix PAGViewListener callback unexpected not called

### PR DESCRIPTION
**Pull request by zeinx920**
#2487

### CODE REVIEW

**Comment by Hparty** [comment]
PAGViewController cannot hold PAGViewListener. Doing so may lead to a circular reference. If this is needed, it is recommended that the business holds the PAGViewListener itself. This cannot be merged.

**Comment by zeinx920** [comment]
> PAGViewController cannot hold PAGViewListener. Doing so may lead to a circular reference. If this is needed, it is recommended that the business holds the PAGViewListener itself. This cannot be merged.

现在PAGViewListener回调有问题，复杂场景下const listener = weakListener.deref()取出的时候会变成null导致listener.onAnimationEnd(this)执行不了

**Comment by Hparty** [comment]
> > PAGViewController cannot hold PAGViewListener. Doing so may lead to a circular reference. If this is needed, it is recommended that the business holds the PAGViewListener itself. This cannot be merged.
> 
> 现在PAGViewListener回调有问题，复杂场景下const listener = weakListener.deref()取出的时候会变成null导致listener.onAnimationEnd(this)执行不了

检查一下listener的生命周期，看上去是listener已经释放了，这时候确实不应该回调了。listener的生命周期应该由业务控制，PAGViewController不应该直接持有listener

**Comment by zeinx920** [comment]
> > > PAGViewController cannot hold PAGViewListener. Doing so may lead to a circular reference. If this is needed, it is recommended that the business holds the PAGViewListener itself. This cannot be merged.
> > 
> > 
> > 现在PAGViewListener回调有问题，复杂场景下const listener = weakListener.deref()取出的时候会变成null导致listener.onAnimationEnd(this)执行不了
> 
> 检查一下listener的生命周期，看上去是listener已经释放了，这时候确实不应该回调了。listener的生命周期应该由业务控制，PAGViewController不应该直接持有listener

好的，感谢回复

**Pull request closed without merging**
